#
#    Makefile のチップ依存部（PolarFire SoC 用）
#
#  $Id: Makefile.chip 335 2023-04-18 10:50:40Z ertl-honda $
# 

#
#  GNU開発環境のターゲットアーキテクチャの定義
#
GCC_TARGET = riscv64-unknown-elf

#
#  チップ依存部ディレクトリ名の定義
#
CHIPDIR = $(SRCDIR)/arch/$(CORE)_$(TOOL)/$(CHIP)

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CHIPDIR)
COPTS := $(COPTS) -march=rv64gc -mabi=lp64d -mcmodel=medany -msmall-data-limit=8 \
         -mstrict-align -mno-save-restore -fsigned-char \
         -ffunction-sections -fdata-sections --specs=nano.specs
LDFLAGS := $(LDFLAGS) -nostartfiles
CDEFS := $(CDEFS) 


#
#  カーネルに関する定義
#
KERNEL_DIRS := $(KERNEL_DIRS) $(CHIPDIR)
KERNEL_COBJS := $(KERNEL_COBJS) chip_kernel_impl.o plic_kernel_impl.o mtimer.o msi_ipi.o
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) chip_support.o

#
#  システムサービスに関する定義
#
SYSSVC_DIRS := $(SYSSVC_DIRS) $(CHIPDIR)

#
#  コア依存部
#
include $(SRCDIR)/arch/$(CORE)_$(TOOL)/common/Makefile.core
