#
#		Makefile のチップ依存部（Zynq7000用）
#
#  $Id: Makefile.chip 263 2021-01-08 06:08:59Z ertl-honda $
# 

#
#  チップ依存部ディレクトリ名の定義
#
CHIPDIR = $(SRCDIR)/arch/$(CORE)_$(TOOL)/$(CHIP)

#
#  コンパイルオプション
#
#  カーネルとシステムサービスをFPU命令なしでコンパイルするために，
#  APPL_CFLAGSとLDFLAGSにのみ-mfpu=vfpv3-d16オプションを追加する．
#
INCLUDES := $(INCLUDES) -I$(CHIPDIR)
COPTS := $(COPTS) -mcpu=cortex-a9
APPL_CFLAGS := $(APPL_CFLAGS) -mfpu=vfpv3-d16
LDFLAGS := $(LDFLAGS) -mcpu=cortex-a9 -mfpu=vfpv3-d16
CDEFS := $(CDEFS) -D__TARGET_ARCH_ARM=7

#
#  カーネルに関する定義
#
KERNEL_DIRS := $(KERNEL_DIRS) $(CHIPDIR)
KERNEL_COBJS := $(KERNEL_COBJS) chip_kernel_impl.o mpcore_kernel_impl.o \
									gic_kernel_impl.o pl310.o mpcore_timer.o
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) gic_support.o

#
#  システムサービスに関する定義
#
SYSSVC_DIRS := $(SYSSVC_DIRS) $(CHIPDIR)

#
#  コア依存部
#
include $(SRCDIR)/arch/$(CORE)_$(TOOL)/common/Makefile.core
